language: node_js
node_js:
  - node

notifications:
  slack:
    secure: xWty8Uo6lSFxjzowUh8+XvKaLKHXC3y6rWBtkwV8/op/UHaPRWDuW6EGL0VnavILKQEpcVzY9ieB295Nnn1K2KzTM6XGVnkEkF/Ge7a1CXDpgf8KkV+8rDCEQ3wFqQGOsUO9EQzjFX8D8kHpleEpB7weVQ+7L4m8TYEiTvgl/BExpeypXVeAHvs6XNPhiuUVfHWdL5CNC+2GunlexNitfSU3Up6fgDydBalZd5tpzShU1wjDBskIfzreQVqeEJGGZof+bEkLRKB6r8oBSbJZXRywBKY5gAh4cuK+bjIPhr/B4c7H5beU9BNmGarWtPPubgknBitvj5bgVjKUJ+YofEORoxpphuykMX1dEiekWjaFiFidXPO8AJeoKeWMlcRHSPrmSCd5FhCwv1RCwv5k2R5yYNykB9CRFQ0wprAQbQA90Rdn4d0V+ADrtSzFPkNP7UCf3H3R2o5Gq/n0V9O41G1FjeWk+Xxic9z8Cs0c7N/2eU4V8XsnpLfR+fl4XVxVDqDxkY/MEE16+cRTxoSEZpKbFFUbyi3ZAjGO8y50DMAT9bAi4GxFOXE8dXeubrh26aiO++FJsmxyR59NPZdQ0icAKQ7kU98toM+jXcoWo5aRBVUnaQMJHjhPdWCyhtt06HQSK9TmWexN2soJoOn9VMnRXR7NNmeyypCNUNOapRw=
    exclude:
      if: (fork = true)

install:
  - npm install
  - npm install -g codecov

script:
  - npm test

after_success:
  - codecov
