language: node_js
node_js:
  - node

notifications:
  slack:
    secure: Q8YE5hqsMVsGnj56BHQEGT8ETPQ9nw6g+CXiHM7o4L3/cG88TvTpYI/TFzLEpY9tZMfFaPrJQ/BKjCOBplOVKWhoLs/u/5U0zOH4V5wwhcKVAfD8IP7WfG0YxRK3H3t1aDPj4p2LJbEFIWPNklySMArybVcRkSnAG8y7mCTxUp1Nc899LtBOAX001xNecqZGpJqXvgIWJH1oFsJC8Feb5t/Kt2UVsX1Dwxd0zAvOpaQN+TV3jJfe6C9J/vHarpd5h9udgHdvONZShNUayNoGaliWYzBEDNXZKTL8fE0NtxzKkCzrUos2bGS42LdxAJcD7lIoTWH73HnzyFe0lCf58h6eF5lpM2xy0KDGgYHDZypi6KZrSoEym/4SQH/s5vsXrd0T/p2OkMILxqe/A7PjnFvl12HQwvLEyTdJ8ns5ZiRrPMBoUGTr3xv03vF4aKgAPwy/YoROIIO+OnGE+0EecZGjziSL2Fiilf7wLpFFGPMQNDEhDzaQwCt6DY+8KC86lewDjUsDqBXZguV5K09uZ4NlfPJgiQlY09arNPWMjyFm3hzKfDYhj9pEx3le9CzOd64GoLgvMmPxnOqvgKG8o4QYxvl5a3er0CRXjkyb1e9TOwHBLq7ltQib+JEv7qjO6UnY/y6SNz4D/MSP6+NtEjdL915GshD/Gi+/OMeQI1w=
    if: fork = false

install:
  - npm install
  - npm install -g codecov

script:
  - npm test

after_success:
  - codecov
